### ISSUE TITLE
hide_keyboard doesn't work on iOS

### ISSUE THREAD

**Issue by hujosh** [appium/python-client#249] opened 2018-09-05 02:29 UTC
Python 3.7.0
Appium Desktop 1.8.1
automationName: XCUITest
platformName: iOS
platformVersion: 11.4
device: iPhone X
Selenium: 3.14.0
Appium-Python-Client: 0.28

hide_keyboard doesn't hide the keyboard.

Thanks

**Comment by mykola-mokhnach** [comment] 2018-09-05 05:40
Duplicate of https://github.com/appium/appium/issues/11313

**Closed by mykola-mokhnach** 2018-09-05 05:40 UTC
