### ISSUE TITLE
Pip package v1.0.0 almost empty

### ISSUE THREAD

**Issue by Sendery** [appium/python-client#544] opened 2020-05-18 12:13 UTC
**pip package not well formated**

pip install Appium-Python-Client --user
```
Defaulting to user installation because normal site-packages is not writeable
Processing XXXXXXX/.cache/pip/wheels/ff/1a/6b/884aedbf6ccef76e28a831758e192a08f38c72f193a48cf412/Appium_Python_Client-1.0.0-py3-none-any.whl
Collecting selenium<4,>=3.14.1
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Requirement already satisfied: urllib3 in XXXXX/.local/lib/python3.5/site-packages (from selenium<4,>=3.14.1->Appium-Python-Client) (1.25.6)
Installing collected packages: selenium, Appium-Python-Client
Successfully installed Appium-Python-Client-1.0.0 selenium-3.141.0
```

 tree XXXX/.local/lib/python3.5/site-packages/appium/
```
/XXXXXX/.local/lib/python3.5/site-packages/appium/
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-35.pyc
│   └── version.cpython-35.pyc
├── version.py
└── webdriver
    └── py.typed
2 directories, 5 files
```
**Compared with the 0.52:**

```
pip3 install Appium-Python-Client==0.52 --user
Processing /XXXXXX/.cache/pip/wheels/b2/5e/b1/cdef659696c11b1b910930f06ee12103776ec415b9f13f92d8/Appium_Python_Client-0.52-cp35-none-any.whl
Requirement already satisfied: selenium<4,>=3.14.1 in /XXXXX/.local/lib/python3.5/site-packages (from Appium-Python-Client==0.52) (3.141.0)
Requirement already satisfied: urllib3 in /XXXXXX/.local/lib/python3.5/site-packages (from selenium<4,>=3.14.1->Appium-Python-Client==0.52) (1.25.6)
Installing collected packages: Appium-Python-Client
  Attempting uninstall: Appium-Python-Client
    Found existing installation: Appium-Python-Client 1.0.0
    Uninstalling Appium-Python-Client-1.0.0:
      Successfully uninstalled Appium-Python-Client-1.0.0
Successfully installed Appium-Python-Client-0.52
```

```
/XXXXXX/.local/lib/python3.5/site-packages/appium/
├── common
│   ├── exceptions.py
│   ├── helper.py
│   ├── __init__.py
│   ├── logger.py
│   └── __pycache__
│       ├── exceptions.cpython-35.pyc
│       ├── helper.cpython-35.pyc
│       ├── __init__.cpython-35.pyc
│       └── logger.cpython-35.pyc
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-35.pyc
│   ├── saucetestcase.cpython-35.pyc
│   └── version.cpython-35.pyc
├── saucetestcase.py
├── version.py
└── webdriver
    ├── appium_connection.py
    ├── appium_service.py
    ├── applicationstate.py
    ├── clipboard_content_type.py
    ├── common
    │   ├── __init__.py
    │   ├── mobileby.py
    │   ├── multi_action.py
    │   ├── __pycache__
    │   │   ├── __init__.cpython-35.pyc
    │   │   ├── mobileby.cpython-35.pyc
    │   │   ├── multi_action.cpython-35.pyc
    │   │   └── touch_action.cpython-35.pyc
    │   └── touch_action.py
    ├── connectiontype.py
    ├── errorhandler.py
    ├── extensions
    │   ├── action_helpers.py
    │   ├── android
    │   │   ├── activities.py
    │   │   ├── common.py
    │   │   ├── display.py
    │   │   ├── gsm.py
    │   │   ├── __init__.py
    │   │   ├── nativekey.py
    │   │   ├── network.py
    │   │   ├── performance.py
    │   │   ├── power.py
    │   │   ├── __pycache__
    │   │   │   ├── activities.cpython-35.pyc
    │   │   │   ├── common.cpython-35.pyc
    │   │   │   ├── display.cpython-35.pyc
    │   │   │   ├── gsm.cpython-35.pyc
    │   │   │   ├── __init__.cpython-35.pyc
    │   │   │   ├── nativekey.cpython-35.pyc
    │   │   │   ├── network.cpython-35.pyc
    │   │   │   ├── performance.cpython-35.pyc
    │   │   │   ├── power.cpython-35.pyc
    │   │   │   ├── sms.cpython-35.pyc
    │   │   │   └── system_bars.cpython-35.pyc
    │   │   ├── sms.py
    │   │   └── system_bars.py
    │   ├── applications.py
    │   ├── clipboard.py
    │   ├── context.py
    │   ├── device_time.py
    │   ├── execute_driver.py
    │   ├── execute_mobile_command.py
    │   ├── hw_actions.py
    │   ├── images_comparison.py
    │   ├── ime.py
    │   ├── __init__.py
    │   ├── keyboard.py
    │   ├── location.py
    │   ├── log_event.py
    │   ├── __pycache__
    │   │   ├── action_helpers.cpython-35.pyc
    │   │   ├── applications.cpython-35.pyc
    │   │   ├── clipboard.cpython-35.pyc
    │   │   ├── context.cpython-35.pyc
    │   │   ├── device_time.cpython-35.pyc
    │   │   ├── execute_driver.cpython-35.pyc
    │   │   ├── execute_mobile_command.cpython-35.pyc
    │   │   ├── hw_actions.cpython-35.pyc
    │   │   ├── images_comparison.cpython-35.pyc
    │   │   ├── ime.cpython-35.pyc
    │   │   ├── __init__.cpython-35.pyc
    │   │   ├── keyboard.cpython-35.pyc
    │   │   ├── location.cpython-35.pyc
    │   │   ├── log_event.cpython-35.pyc
    │   │   ├── remote_fs.cpython-35.pyc
    │   │   ├── screen_record.cpython-35.pyc
    │   │   ├── session.cpython-35.pyc
    │   │   └── settings.cpython-35.pyc
    │   ├── remote_fs.py
    │   ├── screen_record.py
    │   ├── search_context
    │   │   ├── android.py
    │   │   ├── base_search_context.py
    │   │   ├── custom.py
    │   │   ├── __init__.py
    │   │   ├── ios.py
    │   │   ├── mobile.py
    │   │   ├── __pycache__
    │   │   │   ├── android.cpython-35.pyc
    │   │   │   ├── base_search_context.cpython-35.pyc
    │   │   │   ├── custom.cpython-35.pyc
    │   │   │   ├── __init__.cpython-35.pyc
    │   │   │   ├── ios.cpython-35.pyc
    │   │   │   ├── mobile.cpython-35.pyc
    │   │   │   └── windows.cpython-35.pyc
    │   │   └── windows.py
    │   ├── session.py
    │   └── settings.py
    ├── __init__.py
    ├── mobilecommand.py
    ├── __pycache__
    │   ├── appium_connection.cpython-35.pyc
    │   ├── appium_service.cpython-35.pyc
    │   ├── applicationstate.cpython-35.pyc
    │   ├── clipboard_content_type.cpython-35.pyc
    │   ├── connectiontype.cpython-35.pyc
    │   ├── errorhandler.cpython-35.pyc
    │   ├── __init__.cpython-35.pyc
    │   ├── mobilecommand.cpython-35.pyc
    │   ├── switch_to.cpython-35.pyc
    │   ├── webdriver.cpython-35.pyc
    │   └── webelement.cpython-35.pyc
    ├── switch_to.py
    ├── webdriver.py
    └── webelement.py

13 directories, 116 files

```

**Comment by mykola-mokhnach** [comment] 2020-05-18 12:15
Duplicate of https://github.com/appium/python-client/issues/542

**Closed by mykola-mokhnach** 2020-05-18 12:15 UTC
