### ISSUE TITLE
Handle iOS deep link alert?

### ISSUE THREAD

**Issue by paulaladdin** [appium/python-client#121] opened 2016-02-10 18:44 UTC
Hello, I'm an automation engineer at Lyft trying to automate testing deep links in iOS.  I've managed to get everything working up until the point where we must accept the iOS alert dialog (picture attached).  

The issue is that:

--Appium hangs indefinitely on `info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()`. (Eventually triggers session timeout)

--Trying to refresh Appium Inspector when this alert dialog is up also results in an indefinite hang.

--Searching for any page elements results also in an indefinite hang

--Attempting to tap by coordinates also results in an indefinite hang.

After researching this issue online, I tried adding these values to my desired capabilities:

```
autoAcceptAlerts: true,
waitForAppScript: true
```

But they had no practical effect.

We've already invested a significant amount of effort into making this work and have had success on Android, and this seems to the be the only issue still blocking us on iOS.  Any help or insight would be greatly appreciated.

Full log attached.  FYI we're using the Python bindings.

![ios_alert](https://cloud.githubusercontent.com/assets/5489083/12957672/bff2af68-cfe2-11e5-89ba-08d3649a074a.png)

[appiumlog.txt](https://github.com/appium/python-client/files/125319/appiumlog.txt)

**Comment by imurchie** [comment] 2016-02-11 17:38
Do you have a way for us to reproduce this? It would be helpful to try to diagnose. Thanks!

**Comment by paulaladdin** [comment] 2016-02-11 20:56
Sure, essentially the code I'm using to test this does the following:

- Open an Appium session with your app under test
- Background the app, open up safari
- Load a URL for a page that contains a deep link.
- Have appium click on a deep link.
- Open and close the bookmarks page (this is apparently an iOS bug).
- At that point, this alert dialog appears.

A couple of caveats:
- The deep link must be a JS button that calls `window.open()` on the link (I haven't been able to get it work with a standard `<a href=>` style link)
- Make sure to switch between `native_app` and `webview` contexts as needed.

Let me know if you have any further questions.

**Comment by paulaladdin** [comment] 2016-02-17 17:47
Any update on this?  We're anxious to find a resolution or workaround; again, this is the only issue blocking complete rollout of this test.

**Comment by imurchie** [comment] 2016-02-17 18:12
I haven't had a chance to try to reproduce, in order to try to find a solution.

**Comment by imurchie** [comment] 2016-02-18 22:22
I can't reproduce this. Mostly because I'm not sure how you get from step 1 to step 2. Something is not working as it should in your set up, because when `background` returns the app ought to be in the foreground again, and clicking on the `safari` button ought to be impossible.

**Comment by sandykaka** [comment] 2016-07-28 21:08
@paulaladdin did you find work around for this problem?

**Comment by sandykaka** [comment] 2016-07-28 21:09
@jlipps I see your comments on similar alert window issues. Do you know work around for above issue by any chance?

**Comment by sandykaka** [comment] 2016-07-28 21:32
@imurchie I'm facing the same problem, any solution for this?

**Comment by KazuCocoa** [comment] 2017-10-14 12:55
As the comment on https://github.com/appium/python-client/issues/121#issuecomment-185951042 and _Alert window from browser not accessible to driver for iOS appium/appium#6702_ , close this issue on here.

**Closed by KazuCocoa** 2017-10-14 12:55 UTC

**Comment by liangway** [comment] 2018-10-08 07:36
Blocked by this too, any solution?
