### ISSUE TITLE
Cleartext not working on android

### ISSUE THREAD

**Issue by krishachetan89** [appium/python-client#81] opened 2015-05-11 14:50 UTC
HI team,
I wanted to check login in my app two times, one for right credentials and one for wrong credentials.
when i click on element for second time and try to clear text, previously entered text is not cleared.

**Comment by imurchie** [comment] 2015-05-11 15:25
Can you provide more information? The server logs would be useful. As would information about what version of the client and server you are using, what sort of app you are testing (iOS? Android?), etc.

**Comment by krishachetan89** [comment] 2015-05-12 08:38
I am using appium 1.4 for windows, Android mobile with android version 4.4.4, Testing Native Android app.
Console log

**Comment by imurchie** [comment] 2015-05-12 15:36
Thanks for the information. In order for me to reproduce, can you tell me what type of element the password field is? I presume it is an `android.widget.EditText` with `inputType="textPassword"`.

**Comment by krishachetan89** [comment] 2015-05-13 09:45
com.android.app1:id/m_passwordTextField with input password

**Comment by imurchie** [comment] 2015-05-15 16:30
Closing this. The issue is on the server side, so I've created an issue there.

Essentially, the problem is that Android's tools return `""` when trying to get the text for a password field. The clear logic assumes that it is already cleared, and stops.

**Closed** 2015-05-15 16:30 UTC
