### ISSUE TITLE
driver.contexts not reliably finding webview

### ISSUE THREAD

**Issue by EricDusseau** [appium/python-client#202] opened 2018-01-23 13:59 UTC
Appium server: 1.7.2
osx: 10.12
Appium-Python-Client==0.26
ios: 11.2

Using the following I would expect to find two views, native and a webview.  The native view is always returned but 9/10 times it fails to return the webview context.  
```
        contexts = self.driver.contexts
        print "List of contexts " + str(contexts)
        webview = contexts[1]
        appview = contexts[0]
        self.driver.switch_to.context(webview)
        print "Switched to " + str(webview)
        # Click on link in webview
        self.driver.find_element_by_xpath('/html/body/p[2]/a').click()
```

Because the only finds the native context it obviously then fails with the following error

```
test_1_sso (__main__.SmokeTest) ... List of contexts [u'NATIVE_APP']
ERROR

======================================================================
ERROR: test_1_sso (__main__.SmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sso_ios.py", line 121, in test_1_sso
    webview = contexts[1]
IndexError: list index out of range

```

**Comment by KazuCocoa** [comment] 2018-01-24 14:15
The response depends on the return value from Appium server.
Can you attach Appium server log when it reproduced? @EricDusseau

**Comment by EricDusseau** [comment] 2018-01-24 15:02
Full appium server log

https://gist.github.com/EricDusseau/c4ba26cb25cd3ce0ee53c69f3aae18f3

**Comment by KazuCocoa** [comment] 2018-01-24 16:10
It looks server-side thing since we can see `No web frames found` and return only `NATIVE_APP`.

```
[info] [JSONWP Proxy] Replacing sessionId 42F54189-0029-4CAF-B568-571F6BC3640A with afb7bd99-d176-4e2c-b507-16c6dec0ce21
[info] [HTTP] <-- POST /wd/hub/session/afb7bd99-d176-4e2c-b507-16c6dec0ce21/element/9960543F-6179-4F99-8725-F13F988D9A9E/click 200 3154 ms - 118 [info] [HTTP] --> GET /wd/hub/session/afb7bd99-d176-4e2c-b507-16c6dec0ce21/contexts {}
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["afb7bd99-d176-4e2c-b507-16c6dec0ce21"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] useNewSafari --> false
[debug] [RemoteDebugger] Debugger socket connected to ::1:27753
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message to remote debugger[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRSimulatorProductVersionKey":"11.2","WIRSimulatorDeviceIdentifierKey":"8D70C934-CA59-471E-AC90-635EC5110283","WIRSimulatorBuildKey":"15C107","WIRSimulatorNameKey":"iPhone"},"__selector":"_rpc_reportSetup:"}'
[debug] [RemoteDebugger] Received response from socket send: '["iPhone","15C107","11.2"]'
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationDictionaryKey":{}},"__selector":"_rpc_reportConnectedApplicationList:"}'
[debug] [RemoteDebugger] Received no apps from remote debugger. Unable to connect.
[debug] [RemoteDebugger] Connected to application
[debug] [RemoteDebugger] Sim name: iPhone
[debug] [RemoteDebugger] Sim build: 15C107
[debug] [RemoteDebugger] Sim platform version: 11.2
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [iOS] No web frames found.
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRDriverDictionaryKey":{}},"__selector":"_rpc_reportConnectedDriverList:"}'
[debug] [RemoteDebugger] Notified of connected drivers: {}.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[info] [HTTP] <-- GET /wd/hub/session/afb7bd99-d176-4e2c-b507-16c6dec0ce21/contexts 200 669 ms - 86 
[info] [HTTP] --> GET /wd/hub/session/afb7bd99-d176-4e2c-b507-16c6dec0ce21/contexts {}
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["afb7bd99-d176-4e2c-b507-16c6dec0ce21"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
```

Anyway, you've also created the same issue on https://github.com/appium/appium/issues/10059 .
Close this from python-client repository because this issue is not for the client.

**Closed by KazuCocoa** 2018-01-24 16:10 UTC
