### ISSUE TITLE
press_keycode not working on 2.10.0

### ISSUE THREAD

**Issue by chrisgraham24** [appium/python-client#866] opened 2023-05-15 19:12 UTC
## The problem

self.driver.press_keycode(key_code) is failing with the below error on 2.10.0 

`E       selenium.common.exceptions.WebDriverException: Message: Unknown mobile command "pressKey". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,clickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording commands are supported.
E       Stacktrace:
E       UnknownCommandError: Unknown mobile command "pressKey". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,clickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording commands are supported.
E           at AndroidUiautomator2Driver.executeMobile (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium-uiautomator2-driver/lib/commands/general.js:190:11)
E           at AndroidUiautomator2Driver.execute (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:10:23)
E           at commandExecutor (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:126:9)
E           at /nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/async-lock/lib/index.js:154:12
E           at AsyncLock._promiseTry (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/async-lock/lib/index.js:287:31)
E           at exec (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/async-lock/lib/index.js:153:9)
E           at AsyncLock.acquire (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/async-lock/lib/index.js:170:3)
E           at AndroidUiautomator2Driver.executeCommand (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:142:39)
E           at runMicrotasks (<anonymous>)
E           at processTicksAndRejections (internal/process/task_queues.js:95:5)
E           at defaultBehavior (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/lib/appium.js:602:14)
E           at ImageElementPlugin.handle (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/uiautomator2/2.10.1/node_modules/@appium/images-plugin/lib/plugin.js:77:12)
E           at /nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/lib/appium.js:647:16
E           at AppiumDriver.executeWrappedCommand (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/lib/appium.js:680:16)
E           at AppiumDriver.executeCommand (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/appium/lib/appium.js:609:17)
E           at asyncHandler (/nix/store/byyx6479hl8mxlz319sifl6b3ili6vr8-appium-2.0.0/packages/base-driver/lib/protocol/protocol.js:313:19)`

## Environment
- Appium version (or git revision) that exhibits the issue: 2.10.0
- Last Appium version that did not exhibit the issue (if applicable): 2.9.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real
- Appium CLI or Appium.app|exe: CLI

**Comment by KazuCocoa** [comment] 2023-05-16 09:10
Perhaps duplicate of https://github.com/appium/python-client/issues/865, moves to the issue

**Closed by KazuCocoa** 2023-05-16 09:10 UTC

**Comment by kakooloukia** [comment] 2023-05-16 09:42
Hi @KazuCocoa ,

I confirm, this is the same issue: 
![image](https://github.com/appium/python-client/assets/52101924/0e430d8d-9991-4acb-b06a-1d3b34c5b138)


Both tickets are closed; Do you plan to make a bugfix or we have to stick to the previous version ?

**Comment by chrisgraham24** [comment] 2023-05-16 11:37
@KazuCocoa I am not sure how that is a solution? How can I get this to work? I need a working solution asap...

**Comment by KazuCocoa** [comment] 2023-05-16 16:26
Just you can use 2.9.0 right now
